version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - JWT_SECRET=6165a17551fe53d3a5f5fcdf1ba365b1db025ed95573a38ad332a1a068e21b81
      - LDX_WATCH_DIR=/ldx
    volumes:
      - ./backend/data:/app/data
      - ./ldx:/ldx
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "8080:80"
  sqlite-viewer:
    image: coleifer/sqlite-web:latest
    ports:
      - "8081:8080"
    volumes:
      - ./backend/data:/data
    command: ["sqlite_web", "/data/app.db", "--host", "0.0.0.0", "--port", "8080"]
    depends_on:
      - backend
